### ISSUE TITLE
0.2 package does not create `libyaml-0.so.2` so link

### ISSUE THREAD

**Issue by igortg** [conda-forge/yaml-feedstock#13]
Issue:

The 0.2.2 version of **yaml** package does not create a symbolic link for `libyaml-0.so.2` (as the version 0.1.7 does). So some of dependents are not working with the latest version of **yaml**.

From what I checked, latest **uwsgi** package and some old version  of **pyyaml** are throwing the following error: `error while loading shared libraries: libyaml-0.so.2: cannot open shared object file: No such file or directory`

By checking the yaml package from other providers, it seems that `libyaml-0.so.2` should be there:
- https://www.archlinux.org/packages/extra/x86_64/libyaml/files/
- https://pkgs.alpinelinux.org/contents?branch=edge&name=yaml&arch=x86_64&repo=main

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main    conda-forge
ca-certificates           2019.11.28           hecc5488_0    conda-forge
certifi                   2019.11.28               py36_0    conda-forge
icu                       64.2                 he1b5a44_1    conda-forge
jansson                   2.11              h516909a_1001    conda-forge
libffi                    3.2.1             he1b5a44_1006    conda-forge
libgcc-ng                 9.2.0                hdf63c60_0    conda-forge
libiconv                  1.15              h516909a_1005    conda-forge
libstdcxx-ng              9.2.0                hdf63c60_0    conda-forge
libxml2                   2.9.10               hee79883_0    conda-forge
ncurses                   6.1               hf484d3e_1002    conda-forge
openssl                   1.0.2t               h14c3975_0    conda-forge
pcre                      8.43                 he1b5a44_0    conda-forge
pip                       19.3.1                   py36_0    conda-forge
python                    3.6.7             hd21baee_1002    conda-forge
readline                  7.0               hf8c457e_1001    conda-forge
setuptools                42.0.2                   py36_0    conda-forge
sqlite                    3.28.0               h8b20d00_0    conda-forge
tk                        8.6.10               hed695b0_0    conda-forge
uwsgi                     2.0.17.1         py36h2184488_1    conda-forge
wheel                     0.33.6                   py36_0    conda-forge
xz                        5.2.4             h14c3975_1001    conda-forge
yaml                      0.2.2                he1b5a44_0    conda-forge
zlib                      1.2.11            h516909a_1006    conda-forge
```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

     active environment : yaml-test
    active env location : /opt/conda/envs/yaml-test
            shell level : 2
       user config file : /root/.condarc
 populated config files : /root/.condarc
          conda version : 4.6.14
    conda-build version : not installed
         python version : 3.7.3.final.0
       base environment : /opt/conda  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /opt/conda/pkgs
                          /root/.conda/pkgs
       envs directories : /opt/conda/envs
                          /root/.conda/envs
               platform : linux-64
             user-agent : conda/4.6.14 requests/2.21.0 CPython/3.7.3 Linux/4.15.0-70-generic debian/9 glibc/2.24
                UID:GID : 0:0
             netrc file : None
           offline mode : False


```
</details>

**Comment by mbargull** [comment]
xref: https://github.com/yaml/libyaml/issues/141

Both Arch and Alpine do not use the CMake build:
- https://git.archlinux.org/svntogit/packages.git/tree/trunk/PKGBUILD?h=packages/libyaml&id=e8ae0b18b00426f0d3d90ad8021f513164dba056
- https://git.alpinelinux.org/aports/tree/main/yaml/APKBUILD?id=902e71fcd3639928d27a16f9b8dbb2118ae15738

@seanyen, unless you know how to convince the CMake build to create the symlinks, can you switch this back to the Autotools build?

**Comment by ocefpaf** [comment]
> @seanyen, unless you know how to convince the CMake build to create the symlinks, can you switch this back to the Autotools build?

:-(

**Comment by mbargull** [comment]
> :-(

Alternative suggestions welcome ;).
(I have too little in-depth knowledge of either build tool to know what the best thing to do is here. Both tools confuse me. At some point I really have to dig into those, I guess; but currently I just can't afford to do that :/ ...)

**Comment by ocefpaf** [comment]
My frowning face was directed to cmake not your suggestions. I'm happy using it only on Windows so we can have better symlinks support and avoid https://github.com/conda-forge/uwsgi-feedstock/pull/32

**Comment by tadeu** [comment]
Related issue: https://github.com/yaml/libyaml/issues/141

**Comment by seanyen** [comment]
@igortg I tried to switch the Linux build script back to using `Autotools`. Let me know if it fixes the `non-Windows` builds linkage issues.

**Comment by mbargull** [comment]
```sh
ls -lA lib/*.so*
lrwxrwxrwx 1 conda conda     18 Dec  2 20:26 lib/libyaml-0.so.2 -> libyaml-0.so.2.0.6
-rwxrwxr-x 1 conda conda 125064 Dec  2 20:26 lib/libyaml-0.so.2.0.6
lrwxrwxrwx 1 conda conda     18 Dec  2 20:26 lib/libyaml.so -> libyaml-0.so.2.0.6
```
Success! Thanks @seanyen.
