### ISSUE TITLE
New build of yaml has wrong library name

### ISSUE THREAD

**Issue by erykoff** [conda-forge/yaml-feedstock#21]
- [ ] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:

The new build of `yaml-feedstock` using cmake creates a library called `libyaml.2.dylib` but the name should be `libyaml-0.2.dylib` (or so for linux).  This has come up before in #13 that cmake doesn't properly create the versioned libraries. 

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

```
</details>

**Comment by jakirkham** [comment]
Recently PR ( https://github.com/conda-forge/yaml-feedstock/pull/20 ) switching to CMake was merged. Maybe another patch is needed?

cc @Tobias-Fischer @traversaro (in case either of you have thoughts)

**Comment by traversaro** [comment]
Probably we can just set the desired library name in CMake via a patch that sets the [`OUTPUT_NAME`](https://cmake.org/cmake/help/latest/prop_tgt/OUTPUT_NAME.html). If this matches the SONAME, probably this means that we can then remove the custom `patchelf` step.

**Comment by luyang93** [comment]
Need libyaml-0.so.2,
but only libyaml.so, libyaml.so.2.

**Comment by beckermr** [comment]
I am marking this build as broken. Hopefully the next one gets fixed.

**Comment by jakirkham** [comment]
Thanks for taking care of that Matt! Was about to suggest that (since we would want to pull them regardless).

**Comment by traversaro** [comment]
> I am marking this build as broken. Hopefully the next one gets fixed.

Thanks @beckermr !
